### ISSUE TITLE
Bogus reading code?

### ISSUE THREAD

**Issue by LudovicRousseau** [springcard/springcard-ccid-tcp#5]
I guess this code is bogus https://github.com/springcard/springcard-ccid-tcp/blob/master/src/ccid_network.c#L516
```java
  offset = 0; 
  try = 0;  
full_dd: 
  rv = read(networkDevice[reader_index].dev_handle,&device_descriptor[offset],DESC_DEVICE_LEN-offset);
  if ( rv != DESC_DEVICE_LEN )
  {
    try++;
    if( rv > 0 && try < 10)
    {
	goto full_dd;
    }
    DEBUG_COMM("Unable to get proper device descriptor");  
    DEBUG_INFO3("Unable to get proper device descriptor %d %d", rv, DESC_DEVICE_LEN ); 
    close(networkDevice[reader_index].dev_handle);
    networkDevice[reader_index].dev_handle = -1;
    return STATUS_UNSUCCESSFUL;    
  }
```

If you do not `read()` DESC_DEVICE_LEN bytes but say only 5 bytes on the first try then you try to `read()` again. OK.
But:
- offset is not updated so you overwrite the previously read 5 bytes
- you will read at most (DESC_DEVICE_LEN - 5) bytes so the test `rv != DESC_DEVICE_LEN` is now wrong

**Comment by vjardin** [comment]
+1 with Ludovic
